---
# tasks file for pritunl

  - name: Check OS - CentOS / RHEL / Fedora
    include: rhel.yml
    when: ansible_os_family == "RedHat"

  - name: Check OS - Debian
    include: debian.yml
    when: ansible_distribution == "Debian"

  - name: Check OS - Ubuntu 16.XX
    include: ubuntu.yml
    when: 
     - ansible_distribution == "Ubuntu"
     - ansible_distribution_major_version == "16"
